### PR TITLE
fix(update): surface why a startup self-update failed (#545) [superseded by #543 — do not review standalone]

### PR DESCRIPTION
**Pull request by padak**
## Scope, up front

This is **diagnostics, not the fix**. It does not change how the self-update mutates the tool environment, so it does **not** fix the corruption reported in #545 and #528. It removes the reason we cannot diagnose that corruption. Deliberately not marked `Fixes`.

## What

The startup auto-update hook runs the installer with `capture_output=True` and discarded the transcript, so a failed upgrade printed only:

```
Auto-update failed; continuing with current version. Recover with: uv tool install --force ...
```

The explicit `kbagent update` path has always surfaced `result.stderr` (`_update_kbagent` → `message` / `output`). The startup path did not — which is why both Windows reports (#545, 0.76.2 → 0.77.0; #528, three separate upgrades) could say the venv was left broken but not what `uv` actually refused to do.

- `_perform_update()` now returns an `UpdateAttempt` frozen dataclass: `outcome` (the existing `UpdateOutcome`) plus `detail`, the last actionable line of the installer transcript — `stderr`, falling back to `stdout` so the tail is never empty by accident. `OSError` and "no installer on PATH" get their own explanation.
- The failure banner prints it:

```
Auto-update failed (error: Access is denied. (os error 5)); continuing with current version. Recover with: ...
```

- `summarize_failure_tail()` is lifted out of `VersionService._summarize_failure_tail` (now a thin delegate) so both update paths compress a transcript identically.

`TIMEOUT` and `SUCCESS` carry no detail, and a failure with nothing to report keeps the old wording — no empty parentheses.

## Why this matters for #545 / #528

Both reports describe the same failure mode: the update fails partway and leaves the uv tool venv stranded between versions (`ImportError: cannot import name 'rich_utils' from 'typer'`, then `ModuleNotFoundError: No module named 'keboola_agent_cli'`), recoverable only with the printed `uv tool install --force --reinstall` command. What we still do not know is **why `uv` exits non-zero in the first place** — and without the installer's own last line, every new report reproduces that blind spot.

The remaining architectural fix (a fresh-resolution or post-exit detached updater, as suggested in #528) changes what auto-update means on Windows — the current invocation would keep running the old version, with no re-exec and no "What's new" — so it is left as a maintainer decision rather than guessed at here.

## How it was tested

- New `TestPerformUpdateFailureDetail`: stderr tail extraction, stdout fallback, missing-installer and `OSError` explanations, and that a timeout carries no detail.
- New `TestFailureBannerText`: the detail reaches stderr alongside the recovery command, and the banner stays clean when there is no detail.
- New cross-path test in `tests/test_version_service.py`: the module-level helper and the `VersionService` delegate compress a transcript identically.
- Existing `_perform_update` assertions updated for the new return type.
- `make check`: lint + format + changelog-check + full suite (4691 passed, 8 skipped).

Refs #545, #528

### CODE REVIEW

**Comment by padak** [comment]
**Superseded — please read before reviewing.**

This PR was opened by the nightly issue-triage run for #545. After opening it I found #543, which was already in flight for #528 and is the same root cause: the reported broken install in #545 (0.76.2 → 0.77.0, `ImportError: cannot import name 'rich_utils' from 'typer'` → `ModuleNotFoundError: No module named 'keboola_agent_cli'`) is a second report of the non-atomic in-place venv swap #543 fixes properly.

#543 rewrites `_perform_update`, `maybe_auto_update` and the `version_service` failure path, so this branch **conflicts with it** and should not be merged alongside.

Recommendation: **close this** and, if the idea is wanted, fold it into #543 as a small follow-up. The residual value after #543 is narrow but real — on POSIX the inline install stays, `_perform_update` still returns a bare `UpdateOutcome`, and the banner still says only "Auto-update failed" with no reason. What this branch adds there:

- `UpdateAttempt` dataclass carrying the last actionable line of the installer transcript (stderr, falling back to stdout);
- the failure banner printing it: `Auto-update failed (error: Access is denied. (os error 5)); continuing with current version. Recover with: ...`;
- `summarize_failure_tail()` shared by the startup hook and `kbagent update`, so both paths compress a transcript identically.

#545 should be closed as a duplicate of #528 once #543 ships.

**Comment by padak** [comment]
Superseded by #543, which is merged (598eca4). The failure-detail surfacing this PR added shipped as part of that change; closing so it does not linger in the merge queue.
